import { MovementDefinition } from '../types/index';

export const MOVEMENT_DATABASE: MovementDefinition[] = [
  // ==========================================
  // 🏋️ WEIGHTLIFTING (W)
  // ==========================================
  {
    id: 'snatch_full',
    name: 'Squat Snatch',
    modality: 'W',
    primaryPlane: 'OVERHEAD_STABILITY',
    secondaryPlanes: ['HIP_HINGE', 'KNEE_FLEXION'],
    axialLoading: 'MODERATE',
    equipmentRequired: ['barbell_and_plates'],
    defaultRxMen: '61 kg (135 lbs)',
    defaultRxWomen: '43 kg (95 lbs)',
    default1RMKey: 'snatch',
    unit: 'reps',
    videoEmbedId: '9Tlhb_nFFe4',
    videoUrl: 'https://www.youtube.com/watch?v=9Tlhb_nFFe4',
    pointsOfPerformance: {
      setup: 'אחיזה רחבה (Hook Grip), רגליים ברוחב אגן, חזה גאה ושכמות אסופות מעל המוט.',
      execution: 'משיכה סבלנית מהרצפה, פתיחת ירך מתפרצת וצלילה מהירה מתחת למוט לסקוואט עמוק.',
      standards: 'תפיסת המוט בסקוואט מלא מתחת למקביל ועמידה מלאה לנעילה מעל הראש.',
      commonFaults: 'משיכה מוקדמת עם הזרועות, הדיפת המוט קדימה במקום משיכה צמודה לגוף.',
    },
    scalingLadder: [
      'PVC Pipe Overhead Squat & Balance',
      'Dumbbell Hang Power Snatch',
      'Barbell Hang Power Snatch',
      'Power Snatch + Overhead Squat',
      'Squat Snatch (Rx)',
    ],
    substitutions: [
      { targetMovementId: 'db_snatch', notes: 'Dual DB Power Snatch matching weight volume', multiplier: 1 },
      { targetMovementId: 'power_snatch', notes: 'If ankle/hip depth is restricted' },
    ],
    injuryContraindications: ['shoulder_impingement', 'wrist_mobility', 'lower_back', 'ankle_restrictions'],
    coachingCues: [
      'Keep the bar tight against your thighs during the second pull',
      'Violent hip extension before pulling under',
      'Punch the ceiling and lock the shoulders aggressively in the catch',
    ],
  },
  {
    id: 'power_snatch',
    name: 'Power Snatch',
    modality: 'W',
    primaryPlane: 'HIP_HINGE',
    secondaryPlanes: ['OVERHEAD_STABILITY'],
    axialLoading: 'MODERATE',
    equipmentRequired: ['barbell_and_plates'],
    defaultRxMen: '52 kg (115 lbs)',
    defaultRxWomen: '34 kg (75 lbs)',
    default1RMKey: 'powerSnatch',
    unit: 'reps',
    videoEmbedId: 'TL8SM4pAEqU',
    videoUrl: 'https://www.youtube.com/watch?v=TL8SM4pAEqU',
    pointsOfPerformance: {
      setup: 'אחיזת Snatch רחבה, שוקיים אנכיות, כתפיים מעט לפני המוט.',
      execution: 'האצה של המוט מהברכיים אל הירך, פתיחת ירך מהירה ותפיסה מעל מקביל.',
      standards: 'תפיסה מעל גובה מקביל (Above Parallel) ונעילת ירך ומרפקים מלאה.',
      commonFaults: 'כיפוף ידיים מוקדם מדי (Early Arm Bend) ונחיתה בעמידה רחבה מדי.',
    },
    scalingLadder: ['Single DB Snatch', 'Hang Power Snatch', 'Power Snatch (Rx)'],
    substitutions: [
      { targetMovementId: 'db_snatch', notes: 'Alternating Single DB Snatch (22.5/15 kg)' },
      { targetMovementId: 'kb_swing_american', notes: 'KB American Swing for overhead hip power' },
    ],
    injuryContraindications: ['shoulder_impingement', 'wrist_mobility', 'lower_back'],
    coachingCues: [
      'Sweep the bar into the hip pocket',
      'Catch above parallel with active shoulders',
      'Fast cycling: breathe at the top lockout',
    ],
  },
  {
    id: 'clean_and_jerk',
    name: 'Clean & Jerk',
    modality: 'W',
    primaryPlane: 'HIP_HINGE',
    secondaryPlanes: ['KNEE_FLEXION', 'VERTICAL_PUSH'],
    axialLoading: 'HEAVY',
    equipmentRequired: ['barbell_and_plates'],
    defaultRxMen: '61 kg (135 lbs)',
    defaultRxWomen: '43 kg (95 lbs)',
    default1RMKey: 'cleanAndJerk',
    unit: 'reps',
    videoEmbedId: '9xQp2sldyts',
    videoUrl: 'https://www.youtube.com/watch?v=9xQp2sldyts',
    pointsOfPerformance: {
      setup: 'עמידה ברוחב אגן, אחיזת Clean מחוץ לברכיים, מרפקים פרוסים החוצה.',
      execution: 'קלין מהרצפה אל ה-Front Rack, דיפ קצר ואנכי, ודחיקה מתפרצת מעל הראש (Push Jerk / Split Jerk).',
      standards: 'שליטה מלאה במשקל מעל הראש, מרפקים נעולים ורגליים מיושרות בקו אחד.',
      commonFaults: 'קריסה קדימה בדיפ של הג\'רק, פתיחת מרפקים איטית בקלין.',
    },
    scalingLadder: ['Dumbbell Clean & Press', 'Hang Power Clean + Push Press', 'Power Clean & Push Jerk', 'Clean & Jerk (Rx)'],
    substitutions: [
      { targetMovementId: 'db_clean_and_jerk', notes: 'Dual DB Clean & Jerk (2x22.5 / 2x15 kg)' },
      { targetMovementId: 'kb_clean_and_press', notes: 'Dual KB Clean & Push Press' },
    ],
    injuryContraindications: ['wrist_mobility', 'lower_back', 'shoulder_impingement'],
    coachingCues: [
      'Elbows fast through the front rack',
      'Short, vertical dip for the jerk drive',
      'Head through the window on overhead lockout',
    ],
  },
  {
    id: 'power_clean',
    name: 'Power Clean',
    modality: 'W',
    primaryPlane: 'HIP_HINGE',
    secondaryPlanes: ['KNEE_FLEXION'],
    axialLoading: 'MODERATE',
    equipmentRequired: ['barbell_and_plates'],
    defaultRxMen: '61 kg (135 lbs)',
    defaultRxWomen: '43 kg (95 lbs)',
    default1RMKey: 'powerClean',
    unit: 'reps',
    videoEmbedId: 'KwYJTpQ_x5A',
    videoUrl: 'https://www.youtube.com/watch?v=KwYJTpQ_x5A',
    pointsOfPerformance: {
      setup: 'אחיזת Hook Grip ברוחב כתפיים, גב תחתון דרוך ונעול, חזה פתוח.',
      execution: 'משיכה צמודה, סחיטה מהירה בירך ותפיסה מעל מקביל עם מרפקים גבוהים.',
      standards: 'תפיסת המוט על הכתפיים מעל 90 מעלות ועמידה מלאה עד יישור.',
      commonFaults: 'השארת מרפקים נמוכים בתפיסה ומשיכת יתר עם הגב במקום דחף רגליים.',
    },
    scalingLadder: ['DB Hang Clean', 'Hang Power Clean', 'Power Clean (Rx)'],
    substitutions: [
      { targetMovementId: 'db_power_clean', notes: 'Dual DB Power Cleans from floor' },
      { targetMovementId: 'kb_clean_dual', notes: 'Dual KB Power Cleans' },
    ],
    injuryContraindications: ['wrist_mobility', 'lower_back'],
    coachingCues: [
      'Patient first pull past the knees',
      'Jump and shrug before catching',
      'Fast high elbows in the catch',
    ],
  },
  {
    id: 'back_squat',
    name: 'Back Squat',
    modality: 'W',
    primaryPlane: 'KNEE_FLEXION',
    secondaryPlanes: ['HIP_HINGE'],
    axialLoading: 'HEAVY',
    equipmentRequired: ['barbell_and_plates', 'squat_rack'],
    defaultRxMen: '100 kg (225 lbs)',
    defaultRxWomen: '65 kg (145 lbs)',
    default1RMKey: 'backSquat',
    unit: 'reps',
    videoEmbedId: 'ultWZbUMPL8',
    videoUrl: 'https://www.youtube.com/watch?v=ultWZbUMPL8',
    pointsOfPerformance: {
      setup: 'המוט יושב על הטרפזים (High/Low Bar), עמידה ברוחב כתפיים, כפות רגליים פונות מעט החוצה.',
      execution: 'שאיפת בטן עמוקה (Bracing), ירידה עם שליטה בברכיים לכיוון אצבעות הרגליים.',
      standards: 'קפל הירך יורד מתחת לחלק העליון של הברך (Below Parallel) ועמידה לנעילה.',
      commonFaults: 'קריסת ברכיים פנימה, הרמת עקבים או כיפוף יתר של פלג הגוף העליון.',
    },
    scalingLadder: ['Air Squat', 'Goblet Squat', 'Barbell Box Squat', 'Back Squat (Rx)'],
    substitutions: [
      { targetMovementId: 'goblet_squat', notes: 'Heavy KB/DB Goblet Squat' },
      { targetMovementId: 'front_squat', notes: 'Reduces shear on lower back' },
    ],
    injuryContraindications: ['knee_patellar', 'lower_back', 'ankle_restrictions'],
    coachingCues: [
      'Big belly breath and brace 360 degrees',
      'Knees tracking over second toe',
      'Drive out of the hole leading with the chest',
    ],
  },
  {
    id: 'front_squat',
    name: 'Front Squat',
    modality: 'W',
    primaryPlane: 'KNEE_FLEXION',
    secondaryPlanes: ['CORE_ANTERIOR'],
    axialLoading: 'HEAVY',
    equipmentRequired: ['barbell_and_plates', 'squat_rack'],
    defaultRxMen: '84 kg (185 lbs)',
    defaultRxWomen: '57 kg (125 lbs)',
    default1RMKey: 'frontSquat',
    unit: 'reps',
    videoEmbedId: 'uYamuPnT2TQ',
    videoUrl: 'https://www.youtube.com/watch?v=uYamuPnT2TQ',
    pointsOfPerformance: {
      setup: 'המוט מונח על שרירי הדלתואיד הקדמיים, מרפקים מקבילים לרצפה, קצות אצבעות תומכות.',
      execution: 'ירידה אנכית וישרה ככל האפשר עם שמירה על מרפקים גבוהים לכל אורך התנועה.',
      standards: 'ירך מתחת לגובה הברך ועלייה לנעילת ירך וברכיים מלאה.',
      commonFaults: 'נפילת מרפקים מטה שגורמת למוט להחליק ולקריסת עמוד השדרה.',
    },
    scalingLadder: ['DB Front Rack Squat', 'Cross-Arm Barbell Squat', 'Front Squat (Rx)'],
    substitutions: [
      { targetMovementId: 'db_front_squat', notes: 'Dual DB Front Rack Squat' },
      { targetMovementId: 'goblet_squat', notes: 'Single heavy KB in goblet hold' },
    ],
    injuryContraindications: ['wrist_mobility', 'knee_patellar', 'ankle_restrictions'],
    coachingCues: [
      'Elbows high pointing across the room',
      'Maintain an upright vertical torso',
      'Weight balanced midfoot to heel',
    ],
  },
  {
    id: 'overhead_squat',
    name: 'Overhead Squat (OHS)',
    modality: 'W',
    primaryPlane: 'OVERHEAD_STABILITY',
    secondaryPlanes: ['KNEE_FLEXION', 'CORE_ANTERIOR'],
    axialLoading: 'MODERATE',
    equipmentRequired: ['barbell_and_plates'],
    defaultRxMen: '61 kg (135 lbs)',
    defaultRxWomen: '43 kg (95 lbs)',
    default1RMKey: 'overheadSquat',
    unit: 'reps',
    videoEmbedId: 'RD_vUnJnqqI',
    videoUrl: 'https://www.youtube.com/watch?v=RD_vUnJnqqI',
    pointsOfPerformance: {
      setup: 'אחיזה רחבה, מוט נעול בקו האוזניים עם שכמות דוחפות לתקרה (Active Shoulders).',
      execution: 'ירידה בסקוואט מבוקר תוך שמירה על המוט ישירות מעל מרכז כף הרגל.',
      standards: 'עומק מלא מתחת למקביל ושמירה על נעילת מרפקים מוחלטת.',
      commonFaults: 'נפילת המוט קדימה עקב מגבלת תנועתיות בקרסול או בכתפיים.',
    },
    scalingLadder: ['PVC OHS with plate counterbalance', 'Single DB Overhead Squat', 'Overhead Squat (Rx)'],
    substitutions: [
      { targetMovementId: 'single_arm_db_ohs', notes: 'Single Arm DB Overhead Squat' },
      { targetMovementId: 'front_squat', notes: 'If shoulder or thoracic spine is restricted' },
    ],
    injuryContraindications: ['shoulder_impingement', 'wrist_mobility', 'ankle_restrictions'],
    coachingCues: [
      'Press up against the bar constantly (active shoulders)',
      'Armpits facing forward',
      'Descend straight down between the hips',
    ],
  },
  {
    id: 'deadlift',
    name: 'Deadlift',
    modality: 'W',
    primaryPlane: 'HIP_HINGE',
    secondaryPlanes: ['CORE_POSTERIOR'],
    axialLoading: 'HEAVY',
    equipmentRequired: ['barbell_and_plates'],
    defaultRxMen: '102 kg (225 lbs)',
    defaultRxWomen: '70 kg (155 lbs)',
    default1RMKey: 'deadlift',
    unit: 'reps',
    videoEmbedId: 'op9kVnSso6Q',
    videoUrl: 'https://www.youtube.com/watch?v=op9kVnSso6Q',
    pointsOfPerformance: {
      setup: 'מוט צמוד לשוקיים במרכז כף הרגל, אחיזה ברוחב כתפיים, גב ישר ורחב גבי דרוך.',
      execution: 'דחיפת הרצפה עם הרגליים עד גובה הברך, וסגירת ירך חזקה בעמידה.',
      standards: 'עמידה זקופה מלאה עם כתפיים מאחורי המוט ונעילת ברכיים וירך.',
      commonFaults: 'עיגול הגב התחתון (Lumbar Flexion) והתרחקות של המוט מהגוף.',
    },
    scalingLadder: ['KB Deadlift', 'Trap Bar Deadlift', 'Elevated Mat Barbell Deadlift', 'Conventional Deadlift (Rx)'],
    substitutions: [
      { targetMovementId: 'dual_kb_deadlift', notes: 'Dual Kettlebell Suitcase / Conventional Deadlift' },
      { targetMovementId: 'db_romanian_deadlift', notes: 'Dual DB RDL' },
    ],
    injuryContraindications: ['lower_back'],
    coachingCues: [
      'Engage lats by bending the bar into your shins',
      'Push the floor away through the feet',
      'Lock hips and knees simultaneously',
    ],
  },
  {
    id: 'thruster',
    name: 'Thruster',
    modality: 'W',
    primaryPlane: 'KNEE_FLEXION',
    secondaryPlanes: ['VERTICAL_PUSH', 'CORE_ANTERIOR'],
    axialLoading: 'MODERATE',
    equipmentRequired: ['barbell_and_plates'],
    defaultRxMen: '43 kg (95 lbs)',
    defaultRxWomen: '29 kg (65 lbs)',
    default1RMKey: 'thruster',
    unit: 'reps',
    videoEmbedId: 'L219ltL15zk',
    videoUrl: 'https://www.youtube.com/watch?v=L219ltL15zk',
    pointsOfPerformance: {
      setup: 'אחיזת Front Rack, מרפקים מעט נמוכים מאשר בסקוואט רגיל כדי לאפשר לחיצה רציפה.',
      execution: 'פרונט סקוואט מלא אל תוך לחיצה מתפרצת מעל הראש בתנועה אחת חלקה ללא עצירה.',
      standards: 'עומק מתחת למקביל בסקוואט ונעילה מלאה של מרפקים וירך מעל הראש.',
      commonFaults: 'לחיצה מוקדמת של הזרועות לפני סיום דחף הירך, או עצירה בעמידה.',
    },
    scalingLadder: ['DB Thrusters', 'Wall Balls', 'Light Barbell Thrusters', 'Barbell Thruster (Rx)'],
    substitutions: [
      { targetMovementId: 'db_thruster', notes: 'Dual Dumbbell Thrusters (2x15 / 2x10 kg)' },
      { targetMovementId: 'wall_ball', notes: 'Wall Ball Shots (9/6 kg to 10/9 ft)' },
    ],
    injuryContraindications: ['wrist_mobility', 'shoulder_impingement', 'knee_patellar'],
    coachingCues: [
      'Fluid transition from squat drive directly into overhead press',
      'Lock elbows overhead as hips reach full extension',
      'Exhale sharply at the top of every rep',
    ],
  },
  {
    id: 'push_press',
    name: 'Push Press',
    modality: 'W',
    primaryPlane: 'VERTICAL_PUSH',
    secondaryPlanes: ['KNEE_FLEXION'],
    axialLoading: 'MODERATE',
    equipmentRequired: ['barbell_and_plates'],
    defaultRxMen: '52 kg (115 lbs)',
    defaultRxWomen: '34 kg (75 lbs)',
    default1RMKey: 'pushPress',
    unit: 'reps',
    videoEmbedId: 'X6-Y4n9X8h0',
    videoUrl: 'https://www.youtube.com/watch?v=X6-Y4n9X8h0',
    pointsOfPerformance: {
      setup: 'מוט מונח על הכתפיים, גב זקוף לחלוטין, רגליים ברוחב אגן.',
      execution: 'דיפ (Dip) קצר ואנכי עם ברכיים קדימה, דחף ירך חזק ולחיצה מעל הראש.',
      standards: 'נעילת מרפקים מעל הראש עם ראש שעובר קדימה דרך חלון הזרועות.',
      commonFaults: 'כיפוף ברכיים חוזר (Re-dip) שהופך את התנועה לג\'רק במקום פוש-פרס.',
    },
    scalingLadder: ['Strict DB Press', 'DB Push Press', 'Push Press (Rx)'],
    substitutions: [
      { targetMovementId: 'db_push_press', notes: 'Dual DB Push Press' },
      { targetMovementId: 'kb_push_press', notes: 'Dual KB Push Press' },
    ],
    injuryContraindications: ['shoulder_impingement', 'wrist_mobility'],
    coachingCues: [
      'Vertical torso on the dip (no forward lean)',
      'Violent hip snap before pressing with arms',
      'Biceps close to ears at lockout',
    ],
  },
  {
    id: 'db_snatch',
    name: 'Alternating DB Power Snatch',
    modality: 'W',
    primaryPlane: 'HIP_HINGE',
    secondaryPlanes: ['OVERHEAD_STABILITY'],
    axialLoading: 'LOW',
    equipmentRequired: ['dumbbells'],
    defaultRxMen: '22.5 kg (50 lbs)',
    defaultRxWomen: '15 kg (35 lbs)',
    unit: 'reps',
    videoEmbedId: '9520DJiFmvE',
    videoUrl: 'https://www.youtube.com/watch?v=9520DJiFmvE',
    pointsOfPerformance: {
      setup: 'משקולת בין כפות הרגליים, גב ישר ושטוח, יד חופשית אינה נוגעת בגוף.',
      execution: 'דחף ירך והרמת המשקולת צמוד לגוף ("סגירת רוכסן") עד נעילה מעל הראש.',
      standards: 'שני ראשי המשקולת נוגעים ברצפה בכל חזרה, נעילה מלאה והחלפת ידיים תקנית.',
      commonFaults: 'התרחקות המשקולת מהגוף במקום משיכה אנכית, כיפוף גב מוגזם.',
    },
    scalingLadder: ['Single DB Hang Snatch', 'DB Power Snatch (Rx)'],
    substitutions: [
      { targetMovementId: 'kb_snatch_single', notes: 'Single KB Snatch' },
      { targetMovementId: 'kb_swing_american', notes: 'American KB Swing' },
    ],
    injuryContraindications: ['shoulder_impingement', 'lower_back'],
    coachingCues: [
      'Both heads of the dumbbell touch the floor',
      'Zip the jacket - keep the dumbbell close to the body',
      'Switch hands below eye level or on the ground',
    ],
  },
  {
    id: 'wall_ball',
    name: 'Wall Ball Shot',
    modality: 'W',
    primaryPlane: 'KNEE_FLEXION',
    secondaryPlanes: ['VERTICAL_PUSH'],
    axialLoading: 'LOW',
    equipmentRequired: ['wall_ball'],
    defaultRxMen: '9 kg (20 lbs) to 10 ft',
    defaultRxWomen: '6 kg (14 lbs) to 9 ft',
    unit: 'reps',
    videoEmbedId: 'EqjCmsbm-v8',
    videoUrl: 'https://www.youtube.com/watch?v=EqjCmsbm-v8',
    pointsOfPerformance: {
      setup: 'עמידה במרחק זרוע מהקיר, כדור מוחזק בגובה החזה מתחת לסנטר.',
      execution: 'סקוואט מלא מתחת למקביל, וזריקה מתפרצת לקו המטרה על הקיר בעלייה.',
      standards: 'עומק מלא בסקוואט ופגיעת הכדור במרכז המטרה בגובה התקני (10/9 פיט).',
      commonFaults: 'אי שבירת מקביל בסקוואט, תפיסת הכדור כשהוא נופל ללא ספיגה בסקוואט.',
    },
    scalingLadder: ['Medicine Ball Front Squat', 'Lighter Ball / Lower Target', 'Wall Ball (Rx)'],
    substitutions: [
      { targetMovementId: 'db_thruster_light', notes: 'Light DB Thrusters' },
      { targetMovementId: 'jumping_air_squats', notes: 'Jumping Air Squats' },
    ],
    injuryContraindications: ['knee_patellar', 'shoulder_impingement'],
    coachingCues: [
      'Catch the ball on the descent of the squat',
      'Throw off the hip extension drive, not just arms',
      'Relax arms down as the ball flies up',
    ],
  },
  {
    id: 'kb_swing_american',
    name: 'American KB Swing',
    modality: 'W',
    primaryPlane: 'HIP_HINGE',
    secondaryPlanes: ['OVERHEAD_STABILITY'],
    axialLoading: 'LOW',
    equipmentRequired: ['kettlebells'],
    defaultRxMen: '24 kg',
    defaultRxWomen: '16 kg',
    unit: 'reps',
    videoEmbedId: 'mKDiFkp_X54',
    videoUrl: 'https://www.youtube.com/watch?v=mKDiFkp_X54',
    pointsOfPerformance: {
      setup: 'עמידה מעט רחבה מרוחב כתפיים, משקולת מונחת מעט קדימה, שרשרת אחורית דרוכה.',
      execution: 'ציר ירך (Hinge) מהיר, גיוס שרירי ישבן והנפת המשקולת מעל הראש.',
      standards: 'משקולת יציבה ואנכית מעל הראש, מרפקים וברכיים נעולים לחלוטין.',
      commonFaults: 'ביצוע סקוואט במקום ציר ירך, הקשתת יתר בגב התחתון בסיום התנועה.',
    },
    scalingLadder: ['Russian KB Swing (Eye Level)', 'American KB Swing (Rx)'],
    substitutions: [
      { targetMovementId: 'kb_swing_russian', notes: 'Russian KB Swing if shoulder pain' },
      { targetMovementId: 'db_swing', notes: 'Single Dumbbell Swing' },
    ],
    injuryContraindications: ['shoulder_impingement', 'lower_back'],
    coachingCues: [
      'Drive aggressively with glutes and hamstrings',
      'Lockout overhead with vertical bell bottom',
      'Do not squat the swing - hinge at hips',
    ],
  },

  // ==========================================
  // 🤸 GYMNASTICS (G)
  // ==========================================
  {
    id: 'pull_up',
    name: 'Kipping / Butterfly Pull-up',
    modality: 'G',
    primaryPlane: 'VERTICAL_PULL',
    axialLoading: 'NONE',
    equipmentRequired: ['pull_up_bar'],
    unit: 'reps',
    videoEmbedId: 'eGo4IYlbE5g',
    videoUrl: 'https://www.youtube.com/watch?v=eGo4IYlbE5g',
    pointsOfPerformance: {
      setup: 'תלייה מלאה על המתח, אחיזה ברוחב כתפיים, מעבר קצבי בין Hollow ל-Arch.',
      execution: 'פתיחת ירך עוצמתית כלפי מעלה ומשיכה של הסנטר מעל גובה המוט.',
      standards: 'הסנטר עובר במלואו מעל המוט, תלייה מלאה ויישור מרפקים בתחתית.',
      commonFaults: 'אובדן תזמון הקיפ (Kip), חוסר יישור מרפקים בתחתית החזרה.',
    },
    scalingLadder: [
      'Ring Rows (Horizontal)',
      'Jumping Pull-ups',
      'Banded Pull-ups',
      'Strict Pull-ups',
      'Kipping / Butterfly Pull-ups (Rx)',
    ],
    substitutions: [
      { targetMovementId: 'ring_rows', notes: 'Ring Rows (Feet elevated for difficulty)' },
      { targetMovementId: 'db_bent_over_row', notes: 'Dual DB Bent Over Row' },
    ],
    injuryContraindications: ['shoulder_impingement', 'elbow_tendonitis'],
    coachingCues: [
      'Push away from the bar at the top to recycle the kip',
      'Tight core: hollow body to arch transition',
      'Chin clearly over horizontal bar plane',
    ],
  },
  {
    id: 'chest_to_bar',
    name: 'Chest-to-Bar Pull-up (C2B)',
    modality: 'G',
    primaryPlane: 'VERTICAL_PULL',
    axialLoading: 'NONE',
    equipmentRequired: ['pull_up_bar'],
    unit: 'reps',
    videoEmbedId: '04y9P4C9p2o',
    videoUrl: 'https://www.youtube.com/watch?v=04y9P4C9p2o',
    pointsOfPerformance: {
      setup: 'תלייה פעילה בקיפ, יצירת מנוף ירך גבוה ומשיכה עוצמתית עם הרחב גבי.',
      execution: 'משיכת מרפקים חזקה לאחור והובלת בית החזה אל המוט.',
      standards: 'מגע פיזי ברור של בית החזה (מתחת לעצם הבריח) במתח.',
      commonFaults: 'משיכה בלתי מספקת המסתיימת בסנטר בלבד ללא מגע חזה.',
    },
    scalingLadder: ['Pull-ups (Chin over bar)', 'Chest-to-Ring Rows', 'Chest-to-Bar (Rx)'],
    substitutions: [
      { targetMovementId: 'pull_up', notes: 'Standard Pull-ups' },
      { targetMovementId: 'ring_rows_elevated', notes: 'Inverted Ring Rows touching chest' },
    ],
    injuryContraindications: ['shoulder_impingement', 'elbow_tendonitis'],
    coachingCues: [
      'Aggressive hip pop towards the bar',
      'Pull elbows behind ribcage at top apex',
      'Solid physical contact below collarbone',
    ],
  },
  {
    id: 'bar_muscle_up',
    name: 'Bar Muscle-up',
    modality: 'G',
    primaryPlane: 'VERTICAL_PULL',
    secondaryPlanes: ['VERTICAL_PUSH'],
    axialLoading: 'NONE',
    equipmentRequired: ['pull_up_bar'],
    unit: 'reps',
    videoEmbedId: 'qQ2G2o3rKbg',
    videoUrl: 'https://www.youtube.com/watch?v=qQ2G2o3rKbg',
    pointsOfPerformance: {
      setup: 'קיפ עמוק ורחב, דחיפת לטים חזקה כלפי מטה על המתח.',
      execution: 'הרמת ירך גבוהה למוט, מעבר חזה אגרסיבי קדימה (Sit Up) ולחיצה למעלה.',
      standards: 'תמיכה מלאה מעל המוט ונעילת מרפקים מוחלטת.',
      commonFaults: 'עלייה עם מרפק אחד לפני השני (Chicken Wing), חוסר גובה בירך.',
    },
    scalingLadder: [
      'Strict Chest-to-Bar',
      'Low Bar Jumping Muscle-up',
      'Banded Bar Muscle-up',
      'Bar Muscle-up (Rx)',
    ],
    substitutions: [
      { targetMovementId: 'chest_to_bar_plus_dip', notes: '1 C2B + 1 Bar Dip per rep' },
      { targetMovementId: 'chest_to_bar', notes: 'Chest-to-Bar Pull-ups' },
    ],
    injuryContraindications: ['shoulder_impingement', 'wrist_mobility', 'elbow_tendonitis'],
    coachingCues: [
      'Drive hips high to the bar',
      'Fast head-and-chest throw over the bar (sit up)',
      'Aggressive press to full elbow lockout',
    ],
  },
  {
    id: 'ring_muscle_up',
    name: 'Ring Muscle-up',
    modality: 'G',
    primaryPlane: 'VERTICAL_PULL',
    secondaryPlanes: ['VERTICAL_PUSH', 'OVERHEAD_STABILITY'],
    axialLoading: 'NONE',
    equipmentRequired: ['gymnastics_rings'],
    unit: 'reps',
    videoEmbedId: '7_9jXkL2h9s',
    videoUrl: 'https://www.youtube.com/watch?v=7_9jXkL2h9s',
    pointsOfPerformance: {
      setup: 'אחיזת False Grip (ב-Strict) או קיפ דינמי, שמירה על טבעות צמודות לגוף.',
      execution: 'משיכה עמוקה לצלעות, מעבר מהיר (Transition) בלחיצה של הדיפ מעל הטבעות.',
      standards: 'תמיכה יציבה מעל הטבעות, סיבוב כפות ידיים החוצה (Turnout) ונעילה.',
      commonFaults: 'בריחת הטבעות לצדדים ומעבר איטי שמוביל לנפילה מתחת לטבעות.',
    },
    scalingLadder: [
      'Strict Ring Dips & Strict Pull-ups',
      'False Grip Ring Rows + Transitions',
      'Low Ring Foot-Assisted Muscle-up',
      'Ring Muscle-up (Rx)',
    ],
    substitutions: [
      { targetMovementId: 'ring_dip_and_pullup', notes: '1 Strict Pull-up + 1 Ring Dip' },
      { targetMovementId: 'bar_muscle_up', notes: 'Bar Muscle-up if rings unavailable' },
    ],
    injuryContraindications: ['shoulder_impingement', 'elbow_tendonitis'],
    coachingCues: [
      'Strong false grip for strict, or deep dynamic hip extension',
      'Keep rings glued to ribcage during transition',
      'Turn rings out at top support lockout',
    ],
  },
  {
    id: 'toes_to_bar',
    name: 'Toes-to-Bar (T2B)',
    modality: 'G',
    primaryPlane: 'CORE_ANTERIOR',
    secondaryPlanes: ['VERTICAL_PULL'],
    axialLoading: 'NONE',
    equipmentRequired: ['pull_up_bar'],
    unit: 'reps',
    videoEmbedId: '_03pFUegA_0',
    videoUrl: 'https://www.youtube.com/watch?v=_03pFUegA_0',
    pointsOfPerformance: {
      setup: 'תלייה אקטיבית, תנועת קיפ מתואמת של בית החזה קדימה ואחורה.',
      execution: 'דחיפה של המוט מטה, קיפול מהיר של הירך והצלפת אצבעות הרגליים למתח.',
      standards: 'שתי הרגליים נוגעות במוט בו-זמנית בין הידיים, עקבים עוברים לאחור בתחתית.',
      commonFaults: 'נדנוד לא מבוקר, נגיעה ברגל אחת בלבד, אי מעבר עקבים לאחור.',
    },
    scalingLadder: [
      'Hanging Knee Raises',
      'Knees to Elbows',
      'Toes-to-Bar (Rx)',
    ],
    substitutions: [
      { targetMovementId: 'hanging_knee_raise', notes: 'Hanging Knee Raises' },
      { targetMovementId: 'v_ups', notes: 'Floor V-Ups' },
    ],
    injuryContraindications: ['shoulder_impingement', 'lower_back'],
    coachingCues: [
      'Active lat push-down on the bar',
      'Snap toes to bar simultaneously between hands',
      'Flick heels back aggressively to reset the kip rhythm',
    ],
  },
  {
    id: 'hspu_kipping',
    name: 'Kipping Handstand Push-up',
    modality: 'G',
    primaryPlane: 'VERTICAL_PUSH',
    secondaryPlanes: ['OVERHEAD_STABILITY'],
    axialLoading: 'LOW',
    equipmentRequired: [],
    unit: 'reps',
    videoEmbedId: '0wDEO6shVjc',
    videoUrl: 'https://www.youtube.com/watch?v=0wDEO6shVjc',
    pointsOfPerformance: {
      setup: 'עמידת ידיים על הקיר, יצירת משולש (Tripod) בין הראש לידיים.',
      execution: 'הורדת ירך לקיר וכיפוף ברכיים, בעיטה מתפרצת לתקרה תוך לחיצה חזקה ברצפה.',
      standards: 'מגע ראש ברצפה בתחתית, ונעילה מלאה עם עקבים נוגעים בקיר בחלק העליון.',
      commonFaults: 'מיקום ידיים בקו אחד עם הראש, בעיטה מוקדמת לפני לחיצת הידיים.',
    },
    scalingLadder: [
      'Pike Push-ups on Box',
      'Handstand Hold against Wall',
      'Strict HSPU with 1 AbMat',
      'Kipping HSPU (Rx)',
    ],
    substitutions: [
      { targetMovementId: 'db_strict_press', notes: 'Dual Heavy DB Overhead Press' },
      { targetMovementId: 'box_pike_pushup', notes: 'Box Pike Push-ups' },
    ],
    injuryContraindications: ['shoulder_impingement', 'wrist_mobility'],
    coachingCues: [
      'Create a tripod with head and hands on floor',
      'Lower butt to wall, knees to chest',
      'Explosive upward kick along wall while pressing',
    ],
  },
  {
    id: 'handstand_walk',
    name: 'Handstand Walk (HSW)',
    modality: 'G',
    primaryPlane: 'OVERHEAD_STABILITY',
    secondaryPlanes: ['VERTICAL_PUSH', 'CORE_ANTERIOR'],
    axialLoading: 'NONE',
    equipmentRequired: [],
    unit: 'meters',
    videoEmbedId: 'f31lFk_u1kE',
    videoUrl: 'https://www.youtube.com/watch?v=f31lFk_u1kE',
    pointsOfPerformance: {
      setup: 'עמידת ידיים יציבה, גוף דרוך בקו ישר (Hollow), אצבעות פרוסות לרצפה.',
      execution: 'העברת משקל מדודה מצד לצד וצעידה קדימה תוך שמירה על ירך מאוזנת.',
      standards: 'מעבר מרחק ללא נגיעת רגליים ברצפה עד לקו הסימון.',
      commonFaults: 'הקשתת יתר בגב (Scorpion legs) שגורמת לנפילה מהירה קדימה.',
    },
    scalingLadder: [
      'Wall Walks',
      'Shoulder Taps in Handstand',
      '5m Unbroken Handstand Walk',
      'Handstand Walk (Rx)',
    ],
    substitutions: [
      { targetMovementId: 'wall_walks', notes: 'Wall Walks (1 Wall Walk = 5m HSW)' },
      { targetMovementId: 'bear_crawl', notes: 'Bear Crawl' },
    ],
    injuryContraindications: ['wrist_mobility', 'shoulder_impingement'],
    coachingCues: [
      'Reach and pull the floor toward you',
      'Keep tight pointed toes and squeeze glutes',
      'Look between thumbs, not straight ahead',
    ],
  },
  {
    id: 'burpee_over_bar',
    name: 'Burpee Over the Bar',
    modality: 'G',
    primaryPlane: 'HORIZONTAL_PUSH',
    secondaryPlanes: ['KNEE_FLEXION', 'MONOSTRUCTURAL'],
    axialLoading: 'NONE',
    equipmentRequired: ['barbell_and_plates'],
    unit: 'reps',
    videoEmbedId: 'P_3eS3QJ8nI',
    videoUrl: 'https://www.youtube.com/watch?v=P_3eS3QJ8nI',
    pointsOfPerformance: {
      setup: 'עמידה מול המוט (Bar-Facing) או לצד המוט (Lateral).',
      execution: 'ירידה לברפי מלא כשחזה וירכיים נוגעים ברצפה, קפיצה בשתי רגליים מעל המוט.',
      standards: 'מגע חזה ברצפה וקפיצה בשתי רגליים בו-זמנית מעל המוט.',
      commonFaults: 'צעידה מעל המוט במקום קפיצה (אלא אם הוגדר Scaled), אי נגיעת חזה ברצפה.',
    },
    scalingLadder: ['Step-over Burpees', 'Lateral Burpee Over Bar (Rx)'],
    substitutions: [
      { targetMovementId: 'regular_burpee', notes: 'Standard Floor Burpees' },
      { targetMovementId: 'no_pushup_burpee', notes: 'Sprawls / Up-Downs' },
    ],
    injuryContraindications: ['wrist_mobility', 'lower_back'],
    coachingCues: [
      'Chest and thighs hit deck parallel to bar',
      'Stay low as you hop two feet over the barbell',
      'Pivot in the air to face the bar immediately',
    ],
  },
  {
    id: 'box_jump_over',
    name: 'Box Jump Over',
    modality: 'G',
    primaryPlane: 'KNEE_FLEXION',
    secondaryPlanes: ['MONOSTRUCTURAL'],
    axialLoading: 'NONE',
    equipmentRequired: ['plyo_box'],
    defaultRxMen: '24 inch',
    defaultRxWomen: '20 inch',
    unit: 'reps',
    videoEmbedId: '52r_Ul5k03g',
    videoUrl: 'https://www.youtube.com/watch?v=52r_Ul5k03g',
    pointsOfPerformance: {
      setup: 'עמידה מול הקופסה, תנופת ידיים וכיפוף קל בברכיים.',
      execution: 'ניתור בשתי רגליים, נחיתה רכה על הקופסה ומעבר לצד השני.',
      standards: 'ניתור בשתי רגליים יחד, ונחיתה מעבר לקופסה (או ירידה מבוקרת).',
      commonFaults: 'נחיתה נוקשה ברגליים ישרות, ניתור ברגל אחת.',
    },
    scalingLadder: ['Box Step-Overs', 'Box Jump Overs (Rx)'],
    substitutions: [
      { targetMovementId: 'box_step_over', notes: 'Box Step-Overs' },
      { targetMovementId: 'broad_jumps', notes: 'Broad Jumps' },
    ],
    injuryContraindications: ['knee_patellar', 'ankle_restrictions'],
    coachingCues: [
      'Land soft with hips back',
      'Step down or rebound smoothly to maintain pace',
      'Two-foot takeoff required',
    ],
  },
  {
    id: 'double_under',
    name: 'Double Under',
    modality: 'G',
    primaryPlane: 'MONOSTRUCTURAL',
    secondaryPlanes: ['OVERHEAD_STABILITY'],
    axialLoading: 'NONE',
    equipmentRequired: ['jump_rope'],
    unit: 'reps',
    videoEmbedId: '82jNjDS19lg',
    videoUrl: 'https://www.youtube.com/watch?v=82jNjDS19lg',
    pointsOfPerformance: {
      setup: 'מרפקים צמודים לגוף, כפות ידיים מעט לפני האגן, מבט קדימה.',
      execution: 'קפיצה אנכית וגבוהה מכריות כף הרגל, סיבוב כפול ומהיר של פרקי כף היד.',
      standards: 'החבל עובר פעמיים מתחת לרגליים בכל קפיצה בודדת.',
      commonFaults: 'כיפוף ברכיים לאחור (Donkey Kick), פריסת ידיים רחבה לצדדים.',
    },
    scalingLadder: ['Single Unders (x2)', 'High Bounding Single Unders', 'Double Unders (Rx)'],
    substitutions: [
      { targetMovementId: 'single_under', notes: 'Single Unders (2:1 or 3:1 ratio)', multiplier: 2 },
      { targetMovementId: 'plate_hops', notes: 'Plate Hops' },
    ],
    injuryContraindications: ['ankle_restrictions', 'knee_patellar'],
    coachingCues: [
      'Wrists do all the turning, elbows tucked by ribs',
      'Jump vertically with straight legs (no donkey kicking)',
      'Consistent breathing rhythm',
    ],
  },

  // ==========================================
  // 🏃 MONOSTRUCTURAL (M)
  // ==========================================
  {
    id: 'row_c2',
    name: 'Concept2 Row',
    modality: 'M',
    primaryPlane: 'MONOSTRUCTURAL',
    secondaryPlanes: ['HIP_HINGE', 'HORIZONTAL_PULL', 'KNEE_FLEXION'],
    axialLoading: 'LOW',
    equipmentRequired: ['concept2_rower'],
    unit: 'calories',
    videoEmbedId: '40cOaB-hJ3Q',
    videoUrl: 'https://www.youtube.com/watch?v=40cOaB-hJ3Q',
    pointsOfPerformance: {
      setup: 'רגליים רתומות היטב, אחיזה ברוחב כתפיים, שוקיים אנכיות ב-Catch.',
      execution: 'רצף דחף: רגליים ➔ גוף (ציר ירך) ➔ ידיים. חזרה: ידיים ➔ גוף ➔ רגליים.',
      standards: 'צבירת קלוריות או מטרים מדויקת בצג המכשיר.',
      commonFaults: 'כיפוף ברכיים מוקדם מדי בהחזרה (הידיים נתקעות בברכיים), משיכה עם הזרועות בלבד.',
    },
    scalingLadder: ['Row Calories', 'Row Meters'],
    substitutions: [
      { targetMovementId: 'echo_bike', notes: 'Assault / Echo Bike (same cals or 0.8x)', multiplier: 0.8 },
      { targetMovementId: 'skierg', notes: 'Concept2 SkiErg (1:1 cals)', multiplier: 1 },
      { targetMovementId: 'run', notes: '100m Run per 10 Cal Row' },
    ],
    injuryContraindications: ['lower_back'],
    coachingCues: [
      'Legs ➔ Body ➔ Arms on the drive',
      'Arms ➔ Body ➔ Legs on the recovery',
      'Maintain stroke rate around 26-30 s/m for engine pacing',
    ],
  },
  {
    id: 'echo_bike',
    name: 'Assault / Echo Bike',
    modality: 'M',
    primaryPlane: 'MONOSTRUCTURAL',
    secondaryPlanes: ['KNEE_FLEXION', 'HORIZONTAL_PUSH', 'HORIZONTAL_PULL'],
    axialLoading: 'NONE',
    equipmentRequired: ['assault_echo_bike'],
    unit: 'calories',
    videoEmbedId: 'o6jP9qN6t9Y',
    videoUrl: 'https://www.youtube.com/watch?v=o6jP9qN6t9Y',
    pointsOfPerformance: {
      setup: 'גובה מושב מתואם כך שהרגל כמעט ישרה בתחתית הדיווש, אחיזה יציבה בידיות.',
      execution: 'דחיפה ומשיכה מסונכרנת של הידיים והרגליים בקצב RPM קבוע.',
      standards: 'צבירת הקלוריות הרשומה בצג האלקטרוני.',
      commonFaults: 'פתיחת ספרינט של 5 שניות שמובילה לקריסה אירובית מיידית.',
    },
    scalingLadder: ['Echo Bike Calories'],
    substitutions: [
      { targetMovementId: 'row_c2', notes: 'Concept2 Row (1.25x calories)', multiplier: 1.25 },
      { targetMovementId: 'skierg', notes: 'SkiErg' },
    ],
    injuryContraindications: [],
    coachingCues: [
      'Push with legs and pump with arms simultaneously',
      'Do not sprint the first 5 seconds to avoid blowing up',
      'Hold consistent RPMs',
    ],
  },
  {
    id: 'skierg',
    name: 'Concept2 SkiErg',
    modality: 'M',
    primaryPlane: 'MONOSTRUCTURAL',
    secondaryPlanes: ['CORE_ANTERIOR', 'VERTICAL_PULL', 'HIP_HINGE'],
    axialLoading: 'NONE',
    equipmentRequired: ['concept2_skierg'],
    unit: 'calories',
    videoEmbedId: 'yK1Gg5PqUvE',
    videoUrl: 'https://www.youtube.com/watch?v=yK1Gg5PqUvE',
    pointsOfPerformance: {
      setup: 'עמידה ברוחב אגן מול המכשיר, ידיים אוחזות בידיות בגובה העיניים.',
      execution: 'משיכה חזקה מטה תוך כיווץ שרירי הבטן וכיפוף קל בברכיים ובאגן.',
      standards: 'השלמת הקלוריות או המטרים שנקבעו בצג.',
      commonFaults: 'סקוואט עמוק מדי במקום ציר ירך וכיווץ ליבה.',
    },
    scalingLadder: ['SkiErg Calories'],
    substitutions: [
      { targetMovementId: 'row_c2', notes: 'Concept2 Row (1:1 cals)' },
      { targetMovementId: 'echo_bike', notes: 'Echo Bike (0.8x cals)', multiplier: 0.8 },
    ],
    injuryContraindications: ['shoulder_impingement'],
    coachingCues: [
      'High butterfly arm reach',
      'Crunch down through the abs and hinge at hips',
      'Do not squat deep; bend knees slightly',
    ],
  },
  {
    id: 'run',
    name: 'Running',
    modality: 'M',
    primaryPlane: 'MONOSTRUCTURAL',
    secondaryPlanes: ['KNEE_FLEXION', 'HIP_HINGE'],
    axialLoading: 'LOW',
    equipmentRequired: [],
    unit: 'meters',
    videoEmbedId: 'V_Y4eXy_h1Q',
    videoUrl: 'https://www.youtube.com/watch?v=V_Y4eXy_h1Q',
    pointsOfPerformance: {
      setup: 'עמידה זקופה עם נטייה קלה קדימה מהקרסוליים.',
      execution: 'נחיתה על מרכז כף הרגל (Midfoot), קצב צעדים מהיר (Cadence 180).',
      standards: 'מעבר המרחק המוגדר (100m / 200m / 400m / 800m).',
      commonFaults: 'נחיתה כבדה על העקבים (Heel Striking) ומתח בכתפיים ובצוואר.',
    },
    scalingLadder: ['Jog / Walk Intervals', 'Run (Rx)'],
    substitutions: [
      { targetMovementId: 'row_c2', notes: '250m Row per 200m Run' },
      { targetMovementId: 'echo_bike', notes: '15 Cal Bike per 200m Run' },
    ],
    injuryContraindications: ['ankle_restrictions', 'knee_patellar'],
    coachingCues: [
      'Lean slightly from the ankles',
      'Quick cadence: 180 steps/minute',
      'Relax shoulders and jaw',
    ],
  },

  // ==========================================
  // ⚡ ADDITIONAL SUB-MOVEMENTS & OLYMPIC COMPONENTS
  // ==========================================
  {
    id: 'clean_full',
    name: 'Squat Clean',
    modality: 'W',
    primaryPlane: 'HIP_HINGE',
    secondaryPlanes: ['KNEE_FLEXION'],
    axialLoading: 'HEAVY',
    equipmentRequired: ['barbell_and_plates'],
    defaultRxMen: '61 kg (135 lbs)',
    defaultRxWomen: '43 kg (95 lbs)',
    default1RMKey: 'cleanAndJerk',
    unit: 'reps',
    videoEmbedId: 'EKRiWk_1VQE',
    videoUrl: 'https://www.youtube.com/watch?v=EKRiWk_1VQE',
    pointsOfPerformance: {
      setup: 'אחיזת Hook Grip מחוץ לברכיים, שוקיים אנכיות, גב ישר.',
      execution: 'משיכה צמודה, פתיחת ירך מלאה וצלילה מהירה מתחת למוט לסקוואט מלא.',
      standards: 'קפל ירך שובר מקביל בתפיסה ועמידה מלאה עם מרפקים גבוהים.',
      commonFaults: 'משיכה מוקדמת בידיים או תפיסה מעל מקביל והחלקה למטה.',
    },
    scalingLadder: ['Hang Squat Clean', 'Squat Clean (Rx)'],
    substitutions: [{ targetMovementId: 'power_clean', notes: 'Power Clean' }],
    injuryContraindications: ['wrist_mobility', 'lower_back', 'knee_patellar'],
    coachingCues: ['Fast elbows in the hole', 'Drive up leading with elbows'],
  },
  {
    id: 'split_jerk',
    name: 'Split Jerk',
    modality: 'W',
    primaryPlane: 'VERTICAL_PUSH',
    secondaryPlanes: ['OVERHEAD_STABILITY'],
    axialLoading: 'MODERATE',
    equipmentRequired: ['barbell_and_plates'],
    defaultRxMen: '61 kg (135 lbs)',
    defaultRxWomen: '43 kg (95 lbs)',
    default1RMKey: 'cleanAndJerk',
    unit: 'reps',
    videoEmbedId: 'GURx7_nN1uE',
    videoUrl: 'https://www.youtube.com/watch?v=GURx7_nN1uE',
    pointsOfPerformance: {
      setup: 'מוט יושב על הכתפיים, מרפקים מעט קדימה, חזה גבוה.',
      execution: 'דיפ אנכי קצר, דחף מתפרץ ופיסוק רגליים מהיר (Split) מתחת למוט.',
      standards: 'נעילת מרפקים מעל הראש, חזרת רגל קדמית חצי צעד לאחור ואז רגל אחורית קדימה לעמידה מיושרת.',
      commonFaults: 'נטיית גוף קדימה בדיפ, פיסוק צר או קצר מדי שפוגע ביציבות.',
    },
    scalingLadder: ['Push Jerk', 'Split Jerk (Rx)'],
    substitutions: [{ targetMovementId: 'push_jerk', notes: 'Push Jerk' }],
    injuryContraindications: ['shoulder_impingement', 'wrist_mobility'],
    coachingCues: ['Punch the ceiling in the split', 'Recover front foot first'],
  },
  {
    id: 'push_jerk',
    name: 'Push Jerk',
    modality: 'W',
    primaryPlane: 'VERTICAL_PUSH',
    secondaryPlanes: ['KNEE_FLEXION'],
    axialLoading: 'MODERATE',
    equipmentRequired: ['barbell_and_plates'],
    defaultRxMen: '61 kg (135 lbs)',
    defaultRxWomen: '43 kg (95 lbs)',
    default1RMKey: 'cleanAndJerk',
    unit: 'reps',
    videoEmbedId: 'V-hKuAfMXNU',
    videoUrl: 'https://www.youtube.com/watch?v=V-hKuAfMXNU',
    pointsOfPerformance: {
      setup: 'עמידה ברוחב אגן, מוט ב-Front Rack, מרפקים מעט לפנים.',
      execution: 'דיפ אנכי, דחף ירך חד וצניחה מהירה מתחת למוט עם כיפוף ברכיים חוזר (Re-dip).',
      standards: 'תפיסה בברכיים כפופות עם מרפקים נעולים ועמידה ליישור מלא.',
      commonFaults: 'לחיצה איטית ללא צניחה מתחת למוט.',
    },
    scalingLadder: ['Push Press', 'Push Jerk (Rx)'],
    substitutions: [{ targetMovementId: 'push_press', notes: 'Push Press' }],
    injuryContraindications: ['shoulder_impingement', 'wrist_mobility'],
    coachingCues: ['Jump and drop under', 'Lock elbows before feet settle'],
  },
  {
    id: 'hang_power_snatch',
    name: 'Hang Power Snatch',
    modality: 'W',
    primaryPlane: 'HIP_HINGE',
    secondaryPlanes: ['OVERHEAD_STABILITY'],
    axialLoading: 'MODERATE',
    equipmentRequired: ['barbell_and_plates'],
    defaultRxMen: '52 kg (115 lbs)',
    defaultRxWomen: '34 kg (75 lbs)',
    default1RMKey: 'snatch',
    unit: 'reps',
    videoEmbedId: '6sWjB_9qI88',
    videoUrl: 'https://www.youtube.com/watch?v=6sWjB_9qI88',
    pointsOfPerformance: {
      setup: 'עמידה זקופה, מוט מוחזק באחיזת Snatch, ירידה מבוקרת לגובה אמצע הירך/ברכיים.',
      execution: 'פתיחת ירך מתפרצת והנפת המוט מעל הראש בתפיסה מעל 90 מעלות.',
      standards: 'תפיסה מעל מקביל ונעילת מרפקים וירך מלאה.',
      commonFaults: 'חוסר שימוש בירך ומשיכה מוקדמת עם הידיים.',
    },
    scalingLadder: ['DB Hang Snatch', 'Hang Power Snatch (Rx)'],
    substitutions: [{ targetMovementId: 'db_snatch', notes: 'DB Snatch' }],
    injuryContraindications: ['shoulder_impingement', 'lower_back'],
    coachingCues: ['Keep the bar close', 'Violent jump and punch'],
  },
  {
    id: 'strict_press',
    name: 'Strict Press / Shoulder Press',
    modality: 'W',
    primaryPlane: 'VERTICAL_PUSH',
    axialLoading: 'MODERATE',
    equipmentRequired: ['barbell_and_plates'],
    defaultRxMen: '45 kg (95 lbs)',
    defaultRxWomen: '30 kg (65 lbs)',
    default1RMKey: 'strictPress',
    unit: 'reps',
    videoEmbedId: 'XE_H95eA0mY',
    videoUrl: 'https://www.youtube.com/watch?v=XE_H95eA0mY',
    pointsOfPerformance: {
      setup: 'עמידה ברוחב אגן, רגליים וגב נעולים לחלוטין, מרפקים מעט לפני המוט.',
      execution: 'לחיצה ישירה מעל הראש ללא שום עזרה או תנועה מהרגליים.',
      standards: 'נעילת מרפקים מלאה מעל הראש ומעבר ראש קדימה.',
      commonFaults: 'כיפוף ברכיים (Dip) או הקשתת יתר של הגב התחתון.',
    },
    scalingLadder: ['DB Strict Press', 'Barbell Strict Press (Rx)'],
    substitutions: [{ targetMovementId: 'push_press', notes: 'Push Press' }],
    injuryContraindications: ['shoulder_impingement', 'lower_back'],
    coachingCues: ['Squeeze glutes and abs', 'Bar travels in straight vertical line'],
  },
  {
    id: 'bar_dip',
    name: 'Bar Dip / Ring Dip',
    modality: 'G',
    primaryPlane: 'VERTICAL_PUSH',
    axialLoading: 'NONE',
    equipmentRequired: ['pull_up_bar'],
    unit: 'reps',
    videoEmbedId: 'c31f4NknW64',
    videoUrl: 'https://www.youtube.com/watch?v=c31f4NknW64',
    pointsOfPerformance: {
      setup: 'תמיכה במרפקים נעולים מעל המקבילים/טבעות, חזה זקוף.',
      execution: 'ירידה מבוקרת עד שהכתפיים יורדות מתחת לגובה המרפקים (Below 90 deg).',
      standards: 'כתף נמוכה מהמרפק בתחתית, ונעילה מלאה בסיום.',
      commonFaults: 'ירידה רדודה מדי או קריסת כתפיים קדימה.',
    },
    scalingLadder: ['Banded Dips', 'Box Dips', 'Bar Dips (Rx)'],
    substitutions: [{ targetMovementId: 'push_up', notes: 'Push-up' }],
    injuryContraindications: ['shoulder_impingement', 'elbow_tendonitis'],
    coachingCues: ['Keep elbows tucked', 'Full depth then press to lockout'],
  },
  {
    id: 'wall_walks',
    name: 'Wall Walk',
    modality: 'G',
    primaryPlane: 'OVERHEAD_STABILITY',
    secondaryPlanes: ['VERTICAL_PUSH', 'CORE_ANTERIOR'],
    axialLoading: 'NONE',
    equipmentRequired: [],
    unit: 'reps',
    videoEmbedId: 'e8_i7rLh8X0',
    videoUrl: 'https://www.youtube.com/watch?v=e8_i7rLh8X0',
    pointsOfPerformance: {
      setup: 'שכיבה על הבטן, רגליים צמודות לקיר, ידיים מתחת לכתפיים.',
      execution: 'שכיבת סמיכה וטיפוס רגליים על הקיר תוך צעידת ידיים לאחור עד מגע חזה בקיר.',
      standards: 'מגע חזה בקיר וחזרה מבוקרת עד נגיעת חזה ברצפה.',
      commonFaults: 'קריסת ליבה (שקיעת אגן) בהליכה על הקיר.',
    },
    scalingLadder: ['Partial Wall Walk', 'Wall Walk (Rx)'],
    substitutions: [{ targetMovementId: 'handstand_walk', notes: 'Handstand Walk' }],
    injuryContraindications: ['shoulder_impingement', 'wrist_mobility'],
    coachingCues: ['Push tall through shoulders', 'Tight hollow body'],
  },
  {
    id: 'db_thruster',
    name: 'Dual Dumbbell Thruster',
    modality: 'W',
    primaryPlane: 'KNEE_FLEXION',
    secondaryPlanes: ['VERTICAL_PUSH'],
    axialLoading: 'LOW',
    equipmentRequired: ['dumbbells'],
    unit: 'reps',
    videoEmbedId: 'n9P4wB6i-oM',
    videoUrl: 'https://www.youtube.com/watch?v=n9P4wB6i-oM',
    pointsOfPerformance: {
      setup: 'משקולות מונחות על הכתפיים, עמידה ברוחב כתפיים.',
      execution: 'סקוואט מלא ולחיצה מתפרצת של שתי המשקולות מעל הראש בתנועה רציפה.',
      standards: 'שבירת מקביל בסקוואט ונעילה מלאה של זרועות מעל הראש.',
      commonFaults: 'עצירה בין הסקוואט ללחיצה.',
    },
    scalingLadder: ['Light DB Thruster', 'DB Thruster (Rx)'],
    substitutions: [{ targetMovementId: 'thruster', notes: 'Barbell Thruster' }],
    injuryContraindications: ['shoulder_impingement', 'knee_patellar'],
    coachingCues: ['Drive hard with legs', 'Breathe out at top lockout'],
  },
  {
    id: 'hang_squat_snatch',
    name: 'Hang Squat Snatch',
    modality: 'W',
    primaryPlane: 'OVERHEAD_STABILITY',
    secondaryPlanes: ['HIP_HINGE', 'KNEE_FLEXION'],
    axialLoading: 'MODERATE',
    equipmentRequired: ['barbell_and_plates'],
    defaultRxMen: '60 kg (135 lbs)',
    defaultRxWomen: '40 kg (90 lbs)',
    default1RMKey: 'snatch',
    unit: 'reps',
    videoEmbedId: 'TL8SM4pAEqU',
    videoUrl: 'https://www.youtube.com/watch?v=TL8SM4pAEqU',
    pointsOfPerformance: {
      setup: 'מוט מעל הברך (תלייה), אחיזת Snatch רחבה, חזה מורם ושכמות אסופות.',
      execution: 'פתיחת ירך מתפרצת ממיקום התלייה וצלילה מיידית לסקוואט עמוק מתחת למוט.',
      standards: 'תפיסה בסקוואט מתחת לקו הברכיים ונעילה יציבה מעל הראש.',
      commonFaults: 'אי איפוס בנקודת התלייה ומשיכה מוקדמת עם הידיים.',
    },
    scalingLadder: ['Hang Power Snatch + OHS', 'Hang Squat Snatch (Rx)'],
    substitutions: [{ targetMovementId: 'power_snatch', notes: 'If mobility is limited' }],
    injuryContraindications: ['shoulder_impingement', 'wrist_mobility', 'lower_back'],
    coachingCues: ['Patient in the hang', 'Fast aggressive catch'],
  },
  {
    id: 'hang_squat_clean',
    name: 'Hang Squat Clean',
    modality: 'W',
    primaryPlane: 'KNEE_FLEXION',
    secondaryPlanes: ['HIP_HINGE'],
    axialLoading: 'MODERATE',
    equipmentRequired: ['barbell_and_plates'],
    defaultRxMen: '80 kg (175 lbs)',
    defaultRxWomen: '55 kg (120 lbs)',
    default1RMKey: 'cleanAndJerk',
    unit: 'reps',
    videoEmbedId: 'W_oIuK4p748',
    videoUrl: 'https://www.youtube.com/watch?v=W_oIuK4p748',
    pointsOfPerformance: {
      setup: 'מוט מעל הברך, גב ישר, מנח Front Rack מוכן.',
      execution: 'הארכת ירכיים עוצמתית, מרפקים מהירים קדימה ונחיתה בסקוואט קדמי עמוק.',
      standards: 'עמידה מלאה עם מרפקים מורמים מעל גובה המוט.',
      commonFaults: 'מרפקים איטיים שפוגעים בברכיים או נפילה קדימה.',
    },
    scalingLadder: ['Hang Power Clean', 'Hang Squat Clean (Rx)'],
    substitutions: [{ targetMovementId: 'power_clean', notes: 'If wrist/knee limits squat' }],
    injuryContraindications: ['wrist_mobility', 'knee_patellar', 'lower_back'],
    coachingCues: ['Fast elbows', 'Solid landing foot base'],
  },
  {
    id: 'snatch_balance',
    name: 'Snatch Balance',
    modality: 'W',
    primaryPlane: 'OVERHEAD_STABILITY',
    secondaryPlanes: ['KNEE_FLEXION'],
    axialLoading: 'MODERATE',
    equipmentRequired: ['barbell_and_plates'],
    defaultRxMen: '60 kg',
    defaultRxWomen: '40 kg',
    default1RMKey: 'snatch',
    unit: 'reps',
    videoEmbedId: '9Tlhb_nFFe4',
    videoUrl: 'https://www.youtube.com/watch?v=9Tlhb_nFFe4',
    pointsOfPerformance: {
      setup: 'מוט מונח על הטרפזים (Back Rack), אחיזת Snatch רחבה.',
      execution: 'דיפ קל, דחיפת המוט כלפי מעלה וצלילה מהירה מתחתיו לנעילה בסקוואט עמוק.',
      standards: 'נעילת מרפקים מהירה בתחתית הסקוואט ועמידה מלאה.',
      commonFaults: 'דחיפה איטית או היסוס בצלילה מתחת למוט.',
    },
    scalingLadder: ['Heaving Snatch Balance', 'Snatch Balance (Rx)'],
    substitutions: [{ targetMovementId: 'overhead_squat', notes: 'Overhead Squat' }],
    injuryContraindications: ['shoulder_impingement', 'wrist_mobility'],
    coachingCues: ['Punch hard under the bar', 'Aggressive shoulder lock'],
  },
  {
    id: 'floor_press',
    name: 'Barbell Floor Press',
    modality: 'W',
    primaryPlane: 'HORIZONTAL_PUSH',
    axialLoading: 'LOW',
    equipmentRequired: ['barbell_and_plates'],
    defaultRxMen: '80 kg (175 lbs)',
    defaultRxWomen: '50 kg (110 lbs)',
    default1RMKey: 'benchPress',
    unit: 'reps',
    videoEmbedId: 'r91QW6Q5G3E',
    videoUrl: 'https://www.youtube.com/watch?v=r91QW6Q5G3E',
    pointsOfPerformance: {
      setup: 'שכיבה על הרצפה עם ברכיים כפופות, גב מוצמד לרצפה, שכמות אסופות.',
      execution: 'הורדת המוט עד נגיעה עדינה של הזרועות (תלת-ראשי) ברצפה ועצירה לשבריר שנייה, ולחיצה מתפרצת למעלה.',
      standards: 'נגיעת מרפקים/זרועות ברצפה ונעילה מלאה בסיום.',
      commonFaults: 'הקפצת המרפקים מהרצפה.',
    },
    scalingLadder: ['DB Floor Press', 'Barbell Floor Press (Rx)'],
    substitutions: [{ targetMovementId: 'push_up', notes: 'Weighted Push-ups' }],
    injuryContraindications: ['shoulder_impingement'],
    coachingCues: ['Pause on floor', 'Drive through chest & triceps'],
  },
  {
    id: 'rdl_straps',
    name: 'Romanian Deadlift (RDL)',
    modality: 'W',
    primaryPlane: 'HIP_HINGE',
    secondaryPlanes: ['CORE_POSTERIOR'],
    axialLoading: 'HEAVY',
    equipmentRequired: ['barbell_and_plates'],
    defaultRxMen: '100 kg (225 lbs)',
    defaultRxWomen: '70 kg (155 lbs)',
    default1RMKey: 'deadlift',
    unit: 'reps',
    videoEmbedId: '2bS1fN-32H8',
    videoUrl: 'https://www.youtube.com/watch?v=2bS1fN-32H8',
    pointsOfPerformance: {
      setup: 'עמידה זקופה, מוט צמוד לירכיים, אחיזה עם רצועות (Straps).',
      execution: 'שליחת אגן לאחור עם ברכיים מעט רפויות, מתיחת שרירי הירך האחורי ושמירה על קשת מותנית.',
      standards: 'ירידה מבוקרת מתחת לגובה הברך וחזרה לכיווץ ישבן מלא.',
      commonFaults: 'כיפוף יתר של הברכיים (הפיכה לסקוואט) או עיגול הגב.',
    },
    scalingLadder: ['DB Romanian Deadlift', 'Barbell RDL (Rx)'],
    substitutions: [{ targetMovementId: 'deadlift', notes: 'Standard Deadlift' }],
    injuryContraindications: ['lower_back'],
    coachingCues: ['Push hips straight back', 'Keep lats tight and spine neutral'],
  },
  {
    id: 'bulgarian_split_squat',
    name: 'Bulgarian Split Squat',
    modality: 'W',
    primaryPlane: 'KNEE_FLEXION',
    axialLoading: 'LOW',
    equipmentRequired: ['dumbbells', 'bench'],
    unit: 'reps',
    videoEmbedId: '2C-uNgKwPLE',
    videoUrl: 'https://www.youtube.com/watch?v=2C-uNgKwPLE',
    pointsOfPerformance: {
      setup: 'רגל אחת מוגבהת לאחור על ספסל/קופסה, גו זקוף, משקולות בידיים.',
      execution: 'ירידה מבוקרת בסקוואט על הרגל הקדמית עד שהירך מקבילה לרצפה, ודחיפה חזקה דרך העקב.',
      standards: 'ברך אחורית קרובה לרצפה ויישור מלא של הרגל הקדמית.',
      commonFaults: 'קריסת ברך קדמית פנימה.',
    },
    scalingLadder: ['Bodyweight Split Squat', 'Weighted Bulgarian Split Squat (Rx)'],
    substitutions: [{ targetMovementId: 'walking_lunges_weighted', notes: 'Walking Lunges' }],
    injuryContraindications: ['knee_patellar'],
    coachingCues: ['Chest proud', 'Drive through front heel'],
  },
  {
    id: 'sled_pull_drag',
    name: 'Sled Pull & Sled Drag',
    modality: 'M',
    primaryPlane: 'MONOSTRUCTURAL',
    secondaryPlanes: ['KNEE_FLEXION', 'HIP_HINGE'],
    axialLoading: 'NONE',
    equipmentRequired: ['sled'],
    unit: 'meters',
    videoEmbedId: 'Q5-6r-o_wHk',
    videoUrl: 'https://www.youtube.com/watch?v=Q5-6r-o_wHk',
    pointsOfPerformance: {
      setup: 'אחיזה ברצועות המזחלת, גו בהטיה אחידה קדימה או אחורה.',
      execution: 'צעידה רציפה ועוצמתית תוך שמירה על עבודה חזקה של ארבע-ראשי וישבן ללא מנוחה.',
      standards: 'השלמת מרחק המזחלת במלואו.',
      commonFaults: 'עמידה זקופה מדי שמאבדת את מומנטום המשיכה.',
    },
    scalingLadder: ['Light Sled Push', 'Heavy Sled Drag / Pull (Rx)'],
    substitutions: [{ targetMovementId: 'row_concept2', notes: 'Concept2 Row Sprint' }],
    injuryContraindications: [],
    coachingCues: ['Constant drive', 'Short powerful strides'],
  },
  {
    id: 'yoke_carry_hold',
    name: 'Yoke Carry & Yoke Hold',
    modality: 'W',
    primaryPlane: 'MONOSTRUCTURAL',
    secondaryPlanes: ['OVERHEAD_STABILITY', 'CORE_POSTERIOR'],
    axialLoading: 'HEAVY',
    equipmentRequired: ['yoke'],
    defaultRxMen: '180-220 kg',
    defaultRxWomen: '120-150 kg',
    unit: 'meters',
    videoEmbedId: 'fC9N5qN8hU0',
    videoUrl: 'https://www.youtube.com/watch?v=fC9N5qN8hU0',
    pointsOfPerformance: {
      setup: 'יוק ממוקם על הטרפזים העליונים, בטן אסופה, נשימה מלאה ויציאה יציבה מהקרקע.',
      execution: 'צעדים מהירים, קצרים ויציבים קדימה תוך שמירה על יציבות מקסימלית של הגו.',
      standards: 'נשיאת היוק לאורך המרחק ללא הפלה.',
      commonFaults: 'צעדים ארוכים מדי הגורמים לאיבוד שיווי משקל.',
    },
    scalingLadder: ['Heavy Farmer Carry', 'Yoke Carry (Rx)'],
    substitutions: [{ targetMovementId: 'deadlift', notes: 'Heavy Farmer Walk' }],
    injuryContraindications: ['lower_back'],
    coachingCues: ['Fast short feet', 'Brace core 100%'],
  },
  {
    id: 'fat_bar_pull_up',
    name: 'Fat Bar Pull-up',
    modality: 'G',
    primaryPlane: 'VERTICAL_PULL',
    axialLoading: 'NONE',
    equipmentRequired: ['pull_up_bar'],
    unit: 'reps',
    videoEmbedId: 'HRV5Y12xxEw',
    videoUrl: 'https://www.youtube.com/watch?v=HRV5Y12xxEw',
    pointsOfPerformance: {
      setup: 'תלייה על מוט עבה (Fat / Axle Bar), אחיזה הדוקה עם האגודלים.',
      execution: 'משיכה חזקה של הגוף עד שהסנטר עובר את המוט, תוך התמודדות עם עומס אחיזה (Grip) גבוה.',
      standards: 'סנטר עובר מעל המוט ונעילה מלאה למטה.',
      commonFaults: 'איבוד אחיזה והחלקה מהמוט.',
    },
    scalingLadder: ['Fat Bar Ring Rows', 'Fat Bar Pull-ups (Rx)'],
    substitutions: [{ targetMovementId: 'pull_up_strict', notes: 'Strict Pull-ups' }],
    injuryContraindications: ['elbow_tendonitis'],
    coachingCues: ['Squeeze bar like vice', 'Drive elbows to pockets'],
  },
  {
    id: 'fat_bar_t2b',
    name: 'Fat Bar Strict Toes to Bar',
    modality: 'G',
    primaryPlane: 'CORE_ANTERIOR',
    secondaryPlanes: ['VERTICAL_PULL'],
    axialLoading: 'NONE',
    equipmentRequired: ['pull_up_bar'],
    unit: 'reps',
    videoEmbedId: '6dHvTlsMvNY',
    videoUrl: 'https://www.youtube.com/watch?v=6dHvTlsMvNY',
    pointsOfPerformance: {
      setup: 'תלייה סטטית על מוט עבה ללא תנופה (Strict).',
      execution: 'כיווץ בטן עמוק והרמת שתי הרגליים עד מגע בו-זמני של קצות האצבעות במוט.',
      standards: 'מגע ברור של שתי הרגליים במוט בין הידיים ללא קיפינג.',
      commonFaults: 'שימוש בתנופה.',
    },
    scalingLadder: ['Fat Bar Hanging Knee Raises', 'Fat Bar Strict T2B (Rx)'],
    substitutions: [{ targetMovementId: 'toes_to_bar', notes: 'Standard Toes to Bar' }],
    injuryContraindications: ['elbow_tendonitis'],
    coachingCues: ['Strict hollow compression', 'Active shoulders'],
  },
  {
    id: 'devil_press',
    name: 'Dual Dumbbell Devil Press',
    modality: 'W',
    primaryPlane: 'HIP_HINGE',
    secondaryPlanes: ['VERTICAL_PUSH', 'HORIZONTAL_PUSH'],
    axialLoading: 'LOW',
    equipmentRequired: ['dumbbells'],
    defaultRxMen: '2x22.5 kg',
    defaultRxWomen: '2x15 kg',
    unit: 'reps',
    videoEmbedId: '7XqL_u8L5y0',
    videoUrl: 'https://www.youtube.com/watch?v=7XqL_u8L5y0',
    pointsOfPerformance: {
      setup: 'שתי משקולות על הרצפה, שכיבת ברפי כשחזה נוגע ברצפה בין המשקולות.',
      execution: 'קפיצה לרגליים רחבות, הנפת שתי המשקולות בין הרגליים והנפתן הישר מעל הראש בתנועת Snatch אחת חלקה.',
      standards: 'חזה ברצפה ונעילה מלאה של שתי המשקולות מעל הראש.',
      commonFaults: 'הפרדת התנועה ל-Clean ואז Press במקום הנפה רציפה.',
    },
    scalingLadder: ['Single DB Devil Press', 'Dual DB Devil Press (Rx)'],
    substitutions: [{ targetMovementId: 'burpee', notes: 'Burpee Box Jump Overs' }],
    injuryContraindications: ['lower_back', 'shoulder_impingement'],
    coachingCues: ['Aggressive hip snap', 'Lock out directly overhead'],
  },
  {
    id: 'db_l_sit_press',
    name: 'Seated DB L-Sit Press',
    modality: 'W',
    primaryPlane: 'VERTICAL_PUSH',
    secondaryPlanes: ['CORE_ANTERIOR'],
    axialLoading: 'LOW',
    equipmentRequired: ['dumbbells'],
    unit: 'reps',
    videoEmbedId: '2K3u33q8p84',
    videoUrl: 'https://www.youtube.com/watch?v=2K3u33q8p84',
    pointsOfPerformance: {
      setup: 'ישיבה על הרצפה עם רגליים ישרות קדימה במנח L-Sit, משקולות על הכתפיים.',
      execution: 'לחיצה ישרה של המשקולות מעל הראש ללא הישענות לאחור, תוך שמירה על בטן חזקה.',
      standards: 'נעילה מלאה מעל הראש בישיבה זקופה.',
      commonFaults: 'הישענות מוגזמת לאחור.',
    },
    scalingLadder: ['Seated DB Press on Bench', 'Seated Floor L-Sit Press (Rx)'],
    substitutions: [{ targetMovementId: 'strict_press', notes: 'Strict Press' }],
    injuryContraindications: ['lower_back', 'shoulder_impingement'],
    coachingCues: ['Lock your core', 'Press straight up'],
  },
  {
    id: 'bear_walk_db_push',
    name: 'Bear Walk Dumbbell Push',
    modality: 'G',
    primaryPlane: 'HORIZONTAL_PUSH',
    secondaryPlanes: ['CORE_ANTERIOR'],
    axialLoading: 'NONE',
    equipmentRequired: ['dumbbells'],
    unit: 'meters',
    videoEmbedId: '9b-f11q-xL4',
    videoUrl: 'https://www.youtube.com/watch?v=9b-f11q-xL4',
    pointsOfPerformance: {
      setup: 'עמידת 4 (Bear Crawl) עם שתי משקולות בידיים.',
      execution: 'דחיפה של משקולת אחת קדימה תוך התקדמות בצעדי דב, ודחיפת המשקולת השנייה לסירוגין.',
      standards: 'שמירה על ברכיים צמודות לרצפה ללא הרמת אגן מוגזמת.',
      commonFaults: 'הרמת הישבן גבוה מדי.',
    },
    scalingLadder: ['Bear Crawl without weights', 'Bear Walk DB Push (Rx)'],
    substitutions: [{ targetMovementId: 'push_up', notes: 'Push-ups' }],
    injuryContraindications: ['wrist_mobility', 'shoulder_impingement'],
    coachingCues: ['Knees low to floor', 'Brace core'],
  },
  {
    id: 'side_plank_hip_raises',
    name: 'Side Plank Hip Raises',
    modality: 'G',
    primaryPlane: 'CORE_ANTERIOR',
    axialLoading: 'NONE',
    equipmentRequired: [],
    unit: 'reps',
    videoEmbedId: 'pSgO3X3g4mU',
    videoUrl: 'https://www.youtube.com/watch?v=pSgO3X3g4mU',
    pointsOfPerformance: {
      setup: 'פלאנק צדי על האמה, גוף בקו ישר.',
      execution: 'הורדת האגן עד סמוך לרצפה והרמתו למעלה מעבר לקו הישר תוך כיווץ אלכסונים.',
      standards: 'ביצוע מלא של חזרות לכל צד.',
      commonFaults: 'סיבוב בית החזה כלפי הרצפה.',
    },
    scalingLadder: ['Knee Side Plank Hold', 'Side Plank Hip Raises (Rx)'],
    substitutions: [{ targetMovementId: 'v_ups', notes: 'V-Ups' }],
    injuryContraindications: ['shoulder_impingement'],
    coachingCues: ['Squeeze obliques at peak', 'Keep chest open'],
  },
  {
    id: 'synchro_burpees',
    name: 'Synchro Team Burpees',
    modality: 'G',
    primaryPlane: 'HORIZONTAL_PUSH',
    axialLoading: 'NONE',
    equipmentRequired: [],
    unit: 'reps',
    videoEmbedId: 'auBLPXO8Fww',
    videoUrl: 'https://www.youtube.com/watch?v=auBLPXO8Fww',
    pointsOfPerformance: {
      setup: 'שניים או שלושה ספורטאים עומדים זה לצד זה.',
      execution: 'ירידה לברפי יחד, חזה נוגע ברצפה באותו הזמן, וקפיצה למעלה עם מחיאת כף מסונכרנת.',
      standards: 'חזה ברצפה בו-זמנית וקפיצה מסונכרנת.',
      commonFaults: 'חוסר תיאום בעלייה מהרצפה.',
    },
    scalingLadder: ['Standard Burpee', 'Synchro Burpees (Rx)'],
    substitutions: [{ targetMovementId: 'burpee', notes: 'Solo Burpee' }],
    injuryContraindications: [],
    coachingCues: ['Look at your partner', 'Sync the chest touch on the floor'],
  },
  {
    id: 'synchro_gto',
    name: 'Synchro Ground to Overhead',
    modality: 'W',
    primaryPlane: 'HIP_HINGE',
    secondaryPlanes: ['VERTICAL_PUSH'],
    axialLoading: 'LOW',
    equipmentRequired: ['barbell_and_plates'],
    unit: 'reps',
    videoEmbedId: 'n9P4wB6i-oM',
    videoUrl: 'https://www.youtube.com/watch?v=n9P4wB6i-oM',
    pointsOfPerformance: {
      setup: 'ספורטאים עם פלטה/מוט מול הגוף.',
      execution: 'הרמת המשקל מהרצפה ונעילה מסונכרנת מעל הראש.',
      standards: 'נעילת מרפקים מסונכרנת מעל הראש.',
      commonFaults: 'חוסר תיאום בנעילה.',
    },
    scalingLadder: ['Solo Ground to Overhead', 'Synchro GTO (Rx)'],
    substitutions: [{ targetMovementId: 'power_snatch', notes: 'Power Snatch' }],
    injuryContraindications: ['shoulder_impingement'],
    coachingCues: ['Call out cadence', 'Lock out together'],
  },
];
