/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/benchmarks` | `/benchmarks`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/timer` | `/timer`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/today` | `/today`; params?: Router.UnknownInputParams; } | { pathname: `/workout/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/benchmarks` | `/benchmarks`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/timer` | `/timer`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/today` | `/today`; params?: Router.UnknownOutputParams; } | { pathname: `/workout/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/benchmarks${`?${string}` | `#${string}` | ''}` | `/benchmarks${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/timer${`?${string}` | `#${string}` | ''}` | `/timer${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/today${`?${string}` | `#${string}` | ''}` | `/today${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/benchmarks` | `/benchmarks`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/timer` | `/timer`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/today` | `/today`; params?: Router.UnknownInputParams; } | `/workout/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/workout/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
